export const ROUTE_NAMES = {
  DEFAULT: Symbol('DEFAULT'),
  DISCLAIMER: Symbol('DISCLAIMER'),
  //
  ACTIVATE: Symbol('ACTIVATE'),
  INVITE_TRANSACTIONS: Symbol('INVITE_TRANSACTIONS'),
  INVITE: Symbol('INVITE'),
  INVITES_MANAGE: Symbol('INVITES_MANAGE'),
  //
  LOGIN: Symbol('LOGIN'),
  ADMIN: Symbol('ADMIN'),
  REDOWNLOAD: Symbol('REDOWNLOAD'),
  RETICKET: Symbol('RETICKET'),
  PERMISSIONS: Symbol('PERMISSIONS'),
  //
  ACCEPT_TRANSFER: Symbol('ACCEPT_TRANSFER'),
  CANCEL_TRANSFER: Symbol('CANCEL_TRANSFER'),
  POINTS: Symbol('POINTS'),
  POINT: Symbol('POINT'),
  CREATE_GALAXY: Symbol('CREATE_GALAXY'),
  ISSUE_CHILD: Symbol('ISSUE_CHILD'),
  PARTY_SET_POOL_SIZE: Symbol('PARTY_SET_POOL_SIZE'),
  PARTY: Symbol('PARTY'),
  STAR_RELEASE: Symbol('STAR_RELEASE'),
};
