import React from 'react'

import Button from '../components/Button'

class PrivacyPolicy extends React.Component {

  render() {
    const { setGlobalState, lastRoute } = this.props

    return (
      <div>
        <p>
        Effective date: June 01, 2018
        </p>
        <p>
        Tlon Corporation ("us", "we", or "our") operates the website and the Urbit
        mobile application (the "Service").
        </p>
        <p>
        This page informs you of our policies regarding the collection, use, and
        disclosure of personal data when you use our Service and the choices you have
        associated with that data.
        </p>
        <p>
        We use your data to provide and improve the Service. By using the Service, you
        agree to the collection and use of information in accordance with this policy.
        Unless otherwise defined in this Privacy Policy, terms used in this Privacy
        Policy have the same meanings as in our Terms and Conditions.
        </p>
        <p>
        Definitions
        </p>
        <p>
        Service
        </p>
        <p>
        Service means the website and the Urbit mobile application operated by Tlon
        Corporation
        </p>
        <p>
        Personal Data
        </p>
        <p>
        Personal Data means data about a living individual who can be identified from
        those data (or from those and other information either in our possession or
        likely to come into our possession).
        </p>
        <p>
        Usage Data
        </p>
        <p>
        Usage Data is data collected automatically either generated by the use of the
        Service or from the Service infrastructure itself (for example, the duration of
        a page visit).
        </p>
        <p>
        Cookies
        </p>
        <p>
        Cookies are small pieces of data stored on your device (computer or mobile
        device).
        </p>
        <p>
        Data Controller
        </p>
        <p>
        Data Controller means the natural or legal person who (either alone or jointly
        or in common with other persons) determines the purposes for which and the
        manner in which any personal information are, or are to be, processed.
        </p>
        <p>
        For the purpose of this Privacy Policy, we are a Data Controller of your
        Personal Data.
        </p>
        <p>
        Data Processors (or Service Providers)
        </p>
        <p>
        Data Processor (or Service Provider) means any natural or legal person who
        processes the data on behalf of the Data Controller.
        </p>
        <p>
        We may use the services of various Service Providers in order to process your
        data more effectively.
        </p>
        <p>
        Data Subject (or User)
        </p>
        <p>
        Data Subject is any living individual who is using our Service and is the
        subject of Personal Data.
        </p>
        <p>
        Information Collection and Use
        </p>
        <p>
        We collect several different types of information for various purposes to
        provide and improve our Service to you.
        </p>
        <p>
        Types of Data Collected
        </p>
        <p>
        Personal Data
        </p>
        <p>
        While using our Service, we may ask you to provide us with certain personally
        identifiable information that can be used to contact or identify you ("Personal
        Data"). Personally identifiable information may include, but is not limited to:
        </p>
        <p>
        First name and last name
        </p>
        <p>
        Cookies and Usage Data
        </p>
        <p>
        Usage Data
        </p>
        <p>
        We may also collect information that your browser sends whenever you visit our
        Service or when you access the Service by or through a mobile device ("Usage
        Data").
        </p>
        <p>
        This Usage Data may include information such as your computer's Internet
        Protocol address (e.g. IP address), browser type, browser version, the pages of
        our Service that you visit, the time and date of your visit, the time spent on
        those pages, unique device identifiers and other diagnostic data.
        </p>
        <p>
        When you access the Service by or through a mobile device, this Usage Data may
        include information such as the type of mobile device you use, your mobile
        device unique ID, the IP address of your mobile device, your mobile operating
        system, the type of mobile Internet browser you use, unique device identifiers
        and other diagnostic data.
        </p>
        <p>
        Tracking & Cookies Data
        </p>
        <p>
        We use cookies and similar tracking technologies to track the activity on our
        Service and hold certain information.
        </p>
        <p>
        Cookies are files with small amount of data which may include an anonymous
        unique identifier. Cookies are sent to your browser from a website and stored
        on your device. Tracking technologies also used are beacons, tags, and scripts
        to collect and track information and to improve and analyze our Service.
        </p>
        <p>
        You can instruct your browser to refuse all cookies or to indicate when a
        cookie is being sent. However, if you do not accept cookies, you may not be
        able to use some portions of our Service.
        </p>
        <p>
        Examples of Cookies we use:
        </p>
        <p>
        Session Cookies. We use Session Cookies to operate our Service.
        </p>
        <p>
        Preference Cookies. We use Preference Cookies to remember your preferences and
        various settings.
        </p>
        <p>
        Security Cookies. We use Security Cookies for security purposes.
        </p>
        <p>
        Use of Data
        </p>
        <p>
        Tlon Corporation uses the collected data for various purposes:
        </p>
        <p>
        To provide and maintain our Service
        </p>
        <p>
        To notify you about changes to our Service
        </p>
        <p>
        To allow you to participate in interactive features of our Service when you
        choose to do so
        </p>
        <p>
        To provide customer support
        </p>
        <p>
        To gather analysis or valuable information so that we can improve our Service
        </p>
        <p>
        To monitor the usage of our Service
        </p>
        <p>
        To detect, prevent and address technical issues
        </p>
        <p>
        Legal Basis for Processing Personal Data Under General Data Protection
        Regulation (GDPR)
        </p>
        <p>
        If you are from the European Economic Area (EEA), Tlon Corporation legal basis
        for collecting and using the personal information described in this Privacy
        Policy depends on the Personal Data we collect and the specific context in
        which we collect it.
        </p>
        <p>
        Tlon Corporation may process your Personal Data because:
        </p>
        <p>
        We need to perform a contract with you
        </p>
        <p>
        You have given us permission to do so
        </p>
        <p>
        The processing is in our legitimate interests and it's not overridden by your
        rights
        </p>
        <p>
        To comply with the law
        </p>
        <p>
        Retention of Data
        </p>
        <p>
        Tlon Corporation will retain your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will retain and
        use your Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to comply with
        applicable laws), resolve disputes, and enforce our legal agreements and
        policies.
        </p>
        <p>
        Tlon Corporation will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except when this
        data is used to strengthen the security or to improve the functionality of our
        Service, or we are legally obligated to retain this data for longer time
        periods.
        </p>
        <p>
        Transfer of Data
        </p>
        <p>
        Your information, including Personal Data, may be transferred to — and
        maintained on — computers located outside of your state, province, country or
        other governmental jurisdiction where the data protection laws may differ than
        those from your jurisdiction.
        </p>
        <p>
        If you are located outside United States and choose to provide information to
        us, please note that we transfer the data, including Personal Data, to United
        States and process it there.
        </p>
        <p>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
        </p>
        <p>
        Tlon Corporation will take all steps reasonably necessary to ensure that your
        data is treated securely and in accordance with this Privacy Policy and no
        transfer of your Personal Data will take place to an organization or a country
        unless there are adequate controls in place including the security of your data
        and other personal information.
        </p>
        <p>
        Disclosure of Data
        </p>
        <p>
        Legal Requirements
        </p>
        <p>
        Tlon Corporation may disclose your Personal Data in the good faith belief that
        such action is necessary to:
        </p>
        <p>
        To comply with a legal obligation
        </p>
        <p>
        To protect and defend the rights or property of Tlon Corporation
        </p>
        <p>
        To prevent or investigate possible wrongdoing in connection with the Service
        </p>
        <p>
        To protect the personal safety of users of the Service or the public
        </p>
        <p>
        To protect against legal liability
        </p>
        <p>
        Security of Data
        </p>
        <p>
        The security of your data is important to us, but remember that no method of
        transmission over the Internet, or method of electronic storage is 100% secure.
        While we strive to use commercially acceptable means to protect your Personal
        Data, we cannot guarantee its absolute security.
        </p>
        <p>
        "Do Not Track" Signals
        </p>
        <p>
        We do not support Do Not Track ("DNT"). Do Not Track is a preference you can
        set in your web browser to inform websites that you do not want to be tracked.
        </p>
        <p>
        You can enable or disable Do Not Track by visiting the Preferences or Settings
        page of your web browser.
        </p>
        <p>
        Your Data Protection Rights Under General Data Protection Regulation (GDPR)
        </p>
        <p>
        If you are a resident of the European Economic Area (EEA), you have certain
        data protection rights. Tlon Corporation aims to take reasonable steps to allow
        you to correct, amend, delete, or limit the use of your Personal Data.
        </p>
        <p>
        If you wish to be informed what Personal Data we hold about you and if you want
        it to be removed from our systems, please contact us.
        </p>
        <p>
        In certain circumstances, you have the following data protection rights:
        </p>
        <p>
        The right to access, update or to delete the information we have on you.
        Whenever made possible, you can access, update or request deletion of your
        Personal Data directly within your account settings section. If you are unable
        to perform these actions yourself, please contact us to assist you.
        </p>
        <p>
        The right of rectification. You have the right to have your information
        rectified if that information is inaccurate or incomplete.
        </p>
        <p>
        The right to object. You have the right to object to our processing of your
        Personal Data.
        </p>
        <p>
        The right of restriction. You have the right to request that we restrict the
        processing of your personal information.
        </p>
        <p>
        The right to data portability. You have the right to be provided with a copy of
        the information we have on you in a structured, machine-readable and commonly
        used format.
        </p>
        <p>
        The right to withdraw consent. You also have the right to withdraw your consent
        at any time where Tlon Corporation relied on your consent to process your
        personal information.
        </p>
        <p>
        Please note that we may ask you to verify your identity before responding to
        such requests.
        </p>
        <p>
        You have the right to complain to a Data Protection Authority about our
        collection and use of your Personal Data. For more information, please contact
        your local data protection authority in the European Economic Area (EEA).
        </p>
        <p>
        Service Providers
        </p>
        <p>
        We may employ third party companies and individuals to facilitate our Service
        ("Service Providers"), to provide the Service on our behalf, to perform
        Service-related services or to assist us in analyzing how our Service is used.
        </p>
        <p>
        These third parties have access to your Personal Data only to perform these
        tasks on our behalf and are obligated not to disclose or use it for any other
        purpose.
        </p>
        <p>
        Links to Other Sites
        </p>
        <p>
        Our Service may contain links to other sites that are not operated by us. If
        you click on a third party link, you will be directed to that third party's
        site. We strongly advise you to review the Privacy Policy of every site you
        visit.
        </p>
        <p>
        We have no control over and assume no responsibility for the content, privacy
        policies or practices of any third party sites or services.
        </p>
        <p>
        Children's Privacy
        </p>
        <p>
        Our Service does not address anyone under the age of 18 ("Children").
        </p>
        <p>
        We do not knowingly collect personally identifiable information from anyone
        under the age of 18. If you are a parent or guardian and you are aware that
        your child has provided us with Personal Data, please contact us. If we become
        aware that we have collected Personal Data from children without verification
        of parental consent, we take steps to remove that information from our servers.
        </p>
        <p>
        Changes to This Privacy Policy
        </p>
        <p>
        We may update our Privacy Policy from time to time. We will notify you of any
        changes by posting the new Privacy Policy on this page.
        </p>
        <p>
        We will let you know via email and/or a prominent notice on our Service, prior
        to the change becoming effective and update the "effective date" at the top of
        this Privacy Policy.
        </p>
        <p>
        You are advised to review this Privacy Policy periodically for any changes.
        Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
        <p>
        Contact Us
        </p>
        <p>
        If you have any questions about this Privacy Policy, please contact us:
        </p>
        <p>
        By email: support@urbit.org
        </p>

        <div>

          <Button
            className={'btn btn-primary'}
            text={'Close'}
            onClick={ () => setGlobalState({ 'route': lastRoute })}
          />

        </div>

      </div>
    )
  }
}

export default PrivacyPolicy
