import React from 'react';
import ReactDOM from 'react-dom';

import Bridge from './Bridge';

if (process.env.NODE_ENV !== 'production') {
  require('@welldone-software/why-did-you-render')(React);
}

if (process.env.NODE_ENV === 'production') {
  console.log(`
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMWN0kdlc:::::clox0XWMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMN0o;..              .;oONMMMMMMMMMMMMMM
  MMMMMMMMMMMMMKd,.  .':ldkOOOOOkdo:'.   'oKWMMMMMMMMMMM
  MMMMMMMMMMMXo.  .;d0NMMMMMMMMMMMMMN0d;.  .lKMMMMMMMMMM
  MMMMMMMMMWk'  .:OWMMMMMMMMMMMMMMMMMMMW0l.  .xWMMMMMMMM
  MMMMMMMMWd.  ,OWMMMMMMMMMMMMMMMMMMMMMMMW0;  .oNMMMMMMM
  MMMMMMMWx.  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oWMMMMMM
  MMMMMMM0'  ,KMMMMMMMMMWNWMMMMMMMMMMMMMMMMMX:  .OMMMMMM
  MMMMMMWo  .xMMMMMMWOl;'',:oxONMMWOc:clOWMMMk.  lWMMMMM
  MMMMMMN:  '0MMMMMK:          ,loc.   .dWMMMK,  ;XMMMMM
  MMMMMMN:  ,KMMMMK;    ...           .lNMMMMX;  ,KMMMMM
  MMMMMMWc  .OMMMMx.   ,OXKkc;'     .;kNMMMMM0'  :NMMMMM
  MMMMMMMx.  lNMMMN0OOOXMMMMMWN0xddkKWMMMMMMWo   dMMMMMM
  MMMMMMMNc  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.  ;XMMMMMM
  MMMMMMMMK;  .dNMMMMMMMMMMMMMMMMMMMMMMMMMWx.  ,0MMMMMMM
  MMMMMMMMMK:   :0WMMMMMMMMMMMMMMMMMMMMMW0c.  ;0MMMMMMMM
  MMMMMMMMMMNd.  .:kNMMMMMMMMMMMMMMMMMNOc.  .oXMMMMMMMMM
  MMMMMMMMMMMMKo.   'cdOKNWMMMMMWNXOxc'   .l0WMMMMMMMMMM
  MMMMMMMMMMMMMMXx:.    .',;:::;,'.    .:xXMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMXOoc,'..     ...,:okXWMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMWNK00OOO00KNWMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

  Like Urbit? Want to work with us? Try apply@tlon.io.
  `);
}

ReactDOM.render(<Bridge />, document.getElementById('root'));
