name: CI (Build)
on: pull_request
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: ./.nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
